#!/bin/sh

uci -q get ghfu.main >/dev/null || {
    uci -q batch <<EOF
set ghfu.main=ghfu
set ghfu.main.github_repo='smallprogram/OpenWrtAction'
set ghfu.main.selected_release=''
set ghfu.main.keep_config='1'
set ghfu.main.fetch_timeout='15'
set ghfu.main.filter_ext_enabled='1'
set ghfu.main.valid_extensions='.img .img.gz .bin .tar .itb .trx .chk .dlf .ari'
EOF
    uci commit ghfu
}

# Record firmware flash timestamp (recreated on every post-flash first boot)
date +%s > /etc/ghfu_flash_epoch

exit 0
